# Generated by Django 5.2 on 2026-04-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_system_settings_link_to_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="Face_Recognization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face",
                        to="core.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceImageMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("angle", models.CharField(max_length=20)),
                ("capture_time", models.DateTimeField(auto_now_add=True)),
                (
                    "training_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("image_path", models.CharField(max_length=300)),
                ("face_encoding", models.JSONField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
            ],
        ),
    ]
